using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace ImgHub.App.Ui;

/// <summary>
/// 界面文案的本地化（中 / 英 / 日）—— v0.5.40 新增。
///
/// ## 为什么这样设计（AOT 约束 + 实测教训）
///
/// 1. **不能用 .resx / ResourceManager**：
///    .resx 走反射查找资源 → 本项目 AOT 下会炸（CONSTRAINTS H1 同款问题：
///    "Reflection-based serialization has been disabled"/资源找不到，且异常常被吞）。
///    ⇒ 用**普通 C# 字典**，编译期就把字符串嵌进程序集，AOT 无反射。
///
/// 2. **不能用 {DynamicResource}**：
///    实测 Avalonia 的 DynamicResource 只在控件**附加到资源树时**解析一次；
///    之后替换 `Application.Resources` 里的值**不会**推送更新
///    （见 docs/CONSTRAINTS 的 i18n 章节）。那样切语言就得重建整个界面，代价大且易错。
///    ⇒ 用 **INotifyPropertyChanged + 索引器绑定**：切语言 = 通知一次，所有绑定自动刷新。
///
/// 3. **XAML 里的写法**：
///    <code>&lt;TextBlock Text="{CompiledBinding [Key], Source={x:Static ui:Localizer.Instance}}"/&gt;</code>
///    走**编译绑定** → 键名写错会在编译期报 AVLN2000（而不是运行时静默空白）。
///
/// ## 新增文案的步骤
/// 1. 在下面 <see cref="Zh"/> / <see cref="En"/> / <see cref="Ja"/> 各加一条
///    （键 → 译文）；三个字典的键必须一致 —— 有测试钉住（LocalizationContractTests）。
/// 2. XAML/C# 里用同一把键取值。
///
/// ⚠️ 译文说明：英/日文由 AI 按通用术语译出（生成→Generate/生成、蒙版→Mask/マスク……），
///    **未经母语者校对**。要改译文只需改字典，不必动 XAML。
/// </summary>
public sealed class Localizer : INotifyPropertyChanged
{
    /// <summary>单例（XAML 里用 {x:Static ui:Localizer.Instance} 取）。</summary>
    public static Localizer Instance { get; } = new();

    private Localizer() { }

    /// <summary>当前语言（zh / en / ja）。</summary>
    private string _lang = "zh";

    /// <summary>
    /// 语言代码：<c>zh</c> / <c>en</c> / <c>ja</c>。
    ///
    /// ## ⚠️ 索引器通知名必须是 **`Item`**（v0.5.41 实测定位，两轮才查准）
    ///
    /// 走过的弯路（都**不报错**，只能靠"通知后绑定有没有真的刷新"来判定）：
    ///
    /// | 发的通知名 | 结果 |
    /// |---|---|
    /// | `string.Empty`（"所有属性都变了"） | ❌ 不刷新（那是**经典绑定**的约定，编译绑定不认） |
    /// | `Item[key]`（如 `Item[app.title]`） | ❌ 不刷新（**看起来最像，其实是错的**） |
    /// | `Item[]` / `[key]` / `key` | ❌ 不刷新 |
    /// | **`Item`** | ✅ **刷新** ← Avalonia 12 认的就是这个 |
    ///
    /// `Item` 是 C# 索引器的**元数据属性名**（`this[...]` 编译成 `get_Item`/`Item`）。
    /// Avalonia 的绑定监听源对象的 `PropertyChanged("Item")` → 重新求值整个索引器路径。
    ///
    /// ⚠️ **只发一次 `Item` 就够**（不必逐键发 213 次）—— 绑定收到后会用**自己的 key**
    ///   重新调用索引器。所以这里既正确又高效。
    ///
    /// 症状回顾（供后人识别同类问题）：
    ///   代码里 `Localizer["app.title"]` 取值正确、日志正确，但**界面不更新且不报错**。
    /// </summary>
    public string Language
    {
        get => _lang;
        set
        {
            var v = Normalize(value);
            if (v == _lang) return;
            _lang = v;

            // ⚠️ 唯一有效的索引器通知名（见上方表格）；一次即可。
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Language)));
        }
    }

    /// <summary>把外部传入的语言值规整为受支持的代码（未知/空 → zh）。</summary>
    public static string Normalize(string? v) => v?.Trim().ToLowerInvariant() switch
    {
        "en" or "en-us" or "english" => "en",
        "ja" or "ja-jp" or "jp" or "japanese" => "ja",
        _ => "zh",
    };

    /// <summary>
    /// 取文案。XAML 里绑 <c>[Key]</c> 即走这里。
    /// 键不存在时**返回键名本身**（而不是空）——这样界面上会显示 `settings.title` 这类键，
    /// 一眼能看出漏翻译，而不是静默显示空白（静默失败是本项目踩过的坑）。
    /// </summary>
    public string this[string key]
    {
        get
        {
            var table = _lang switch
            {
                "en" => En,
                "ja" => Ja,
                _ => Zh,
            };
            if (table.TryGetValue(key, out var v)) return v;
            // 回退到中文（比显示键名更友好，且中文是"源语言"必然齐全）
            if (Zh.TryGetValue(key, out var zh)) return zh;
            return key;
        }
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>供非 XAML 场景（C# 里拼消息）取文案。</summary>
    public string T(string key) => this[key];

    /// <summary>格式化取文案（<c>{0}</c> 占位）。</summary>
    public string T(string key, params object?[] args)
        => string.Format(System.Globalization.CultureInfo.InvariantCulture, this[key], args);

    // ================================================================ 中文（源语言）
    private static readonly Dictionary<string, string> Zh = new()
    {
        // ---------- 顶栏 / 通用
        ["app.title"] = "ImgHub 工作台",
        ["common.settings"] = "设置",
        ["common.dark"] = "深色",
        ["common.cancel"] = "取消",
        ["common.close"] = "关闭",
        ["common.delete"] = "删除",
        ["common.confirm"] = "确定",
        ["common.ok"] = "好",
        ["common.yes"] = "是",
        ["common.no"] = "否",
        ["common.save"] = "保存",
        ["common.copy"] = "复制",
        ["common.copied"] = "已复制",
        ["common.retry"] = "重试",
        ["common.none"] = "无",
        ["common.unknown"] = "未知",

        // ---------- 主参数卡片
        ["param.model"] = "模型",
        ["param.quality"] = "质量",
        ["param.aspect"] = "画幅",
        ["param.resolution"] = "分辨率",
        ["param.format"] = "格式",
        ["param.batch"] = "批量",
        ["param.prompt"] = "提示词",
        ["param.extract"] = "提取",
        ["param.genParams"] = "生成参数",
        ["param.autoModel"] = "自动选择默认模型",
        ["param.promptPlaceholder"] = "一只猫在窗台上，逆光，胶片感",
        ["param.genPrompt"] = "生成提示",
        ["param.genPromptTip"] = "用 LLM 生成 4 条提示词候选，浮窗里 4 选 1",
        ["param.polish"] = "润色",
        ["param.clear"] = "清空",
        ["param.clearTip"] = "清空提示词与当前标注（不删历史）",
        ["param.extractTipJimeng"] = "即梦素材提取：从当前图提取商品或元素，生成平面图",
        ["param.promptGuideTip"] = "提示词工程指南：当前端点偏好怎么写提示词（总览 / OpenAI / 千问）",

        // ---------- 动作按钮
        ["action.generate"] = "生成",
        ["action.edit"] = "编辑",
        ["action.deleteSelected"] = "删除选中",
        ["action.preview"] = "预览",
        ["action.editImage"] = "编辑图片",

        // ---------- 参考图
        ["ref.title"] = "参考图（编辑时附带）",
        ["ref.keep"] = "保留",
        ["ref.keepTip"] = "勾选 = 参考图长期保留；不勾 = 一次编辑后自动清空（默认）",
        ["ref.add"] = "＋ 添加",
        ["ref.addTip"] = "导入外部图片作为参考图（编辑时一并给模型）",

        // ---------- 提示词历史
        ["promptHist.title"] = "提示词历史（悬停看全文）",
        ["promptHist.deleteSelectedTip"] = "删除选中的提示词记录（需确认）",
        ["promptHist.multiTip"] = "开启后可在列表里多选，批量删除",
        ["promptHist.deleteOneTip"] = "删除该条记录（需确认）",

        // ---------- 预览 / 标注
        ["region.maskHint"] = "用方框/圆圈/马克笔圈出要修改的区域（薄层涂抹，不遮挡原图）",
        ["region.enterHint"] = "点「编辑图片」开始圈画要修改的区域（薄层涂抹，不遮挡原图）",
        ["region.tool"] = "工具",
        ["region.brushSize"] = "粗细",
        ["region.brushTip"] = "调节马克笔笔迹宽度 / 橡皮擦除半径",
        ["region.paletteTip"] = "选择蒙版颜色（16 色）",
        ["region.undo"] = "撤销",
        ["region.undoTip"] = "撤销上一步标注编辑（方框/圆圈/马克笔/橡皮/清除）",
        ["region.redo"] = "重做",
        ["region.redoTip"] = "重做被撤销的标注编辑",
        ["region.zoom"] = "缩放",
        ["region.zoomOutTip"] = "缩小预览（画布缩放）",
        ["region.zoomInTip"] = "放大预览（画布缩放）",
        ["region.center"] = "图片居中",
        ["region.centerTip"] = "把图片复位到预览框中央（缩放/平移归位，快捷键 0）",
        ["region.clear"] = "清除",
        ["region.clearTip"] = "清除全部标注笔画（可撤销）",
        ["region.editWithRegions"] = "用标注编辑",
        ["region.toggleTip"] = "开启区域标注：圈出要修改的地方",
        ["region.toolRect"] = "方框",
        ["region.toolEllipse"] = "圆圈",
        ["region.toolMarker"] = "马克笔",
        ["region.toolEraser"] = "橡皮",
        ["region.none"] = "尚未圈画",
        ["region.count"] = "已标注 {0} 处",

        // ---------- 底栏
        ["bottom.viewer"] = "系统看图器",
        ["bottom.viewerTip"] = "用系统默认看图程序打开当前图片",
        ["bottom.saveGallery"] = "保存到相册",
        ["bottom.saveGalleryTip"] = "把当前图片保存到系统图片目录（需选位置）",
        ["bottom.reveal"] = "定位文件",
        ["bottom.revealTip"] = "在文件管理器中定位这张图片（非 Windows 平台不支持）",
        ["bottom.maskHelp"] = "蒙版说明",
        ["bottom.maskHelpTip"] = "蒙版如何使用、传给服务端的流程、提示词怎么写",
        ["bottom.shortcuts"] = "快捷键",
        ["bottom.shortcutsTip"] = "在消息面板显示可用快捷键提示",
        ["bottom.dataDir"] = "数据目录",
        ["bottom.dataDirTip"] = "在消息面板显示数据目录路径",
        ["bottom.undo"] = "撤回",
        ["bottom.undoTip"] = "从历史列表移除最新一张（磁盘文件保留）",

        // ---------- 消息
        ["msg.title"] = "消息",
        ["msg.stream"] = "流式部分图（SSE）",
        ["msg.selfCheckTip"] = "点击查看逐项自检详情",
        ["msg.cost"] = "累计",
        ["msg.costTip"] = "当前 provider 的累计花费",

        // ---------- 设置面板
        ["settings.title"] = "设置",
        ["settings.api"] = "生图 API",
        ["settings.provider"] = "Provider",
        ["settings.apiKey"] = "API Key",
        ["settings.testKey"] = "校验",
        ["settings.testKeyTip"] = "用当前 key 试调一次接口，验证是否可用",
        ["settings.endpoint"] = "端点",
        ["settings.endpointHint"] = "留空 = 用官方默认端点",
        ["settings.endpointTipQwen"] = "千问可填业务空间专属域名：https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com",
        ["settings.endpointWarnQwen"] = "跨地域/跨业务空间调用会鉴权失败；端点必须与 API Key 同地域",
        ["settings.polish"] = "提示词润色（可选，需自配端点/模型/key）",
        ["settings.polishHint"] = "端点 base_url，如 https://...",
        ["settings.jimengAkSk"] = "即梦用火山引擎 AK/SK 签名鉴权，需要 AccessKeyId + SecretAccessKey 两个值",
        ["settings.jimengWhere"] = "两把密钥都来自火山引擎控制台 → 访问密钥（IAM）",
        ["settings.secretAccessKey"] = "SecretAccessKey（火山引擎「访问密钥」里的私钥）",
        ["settings.theme"] = "主题",
        ["settings.darkTheme"] = "深色主题",
        ["settings.hoverAnim"] = "悬停动画",
        ["settings.tooltips"] = "悬停说明（ToolTip）",
        ["settings.language"] = "语言 / Language",

        // ---------- 确认浮层
        ["confirm.discardTip"] = "放弃本次修改并关闭浮层",

        // ---------- v0.5.40 补充：界面其余文案（ToolTip / 设置 / 高级参数等）
        ["region.palette"] = "调色板",
        ["settings.darkTip"] = "切换深色 / 浅色主题",
        ["top.settingsTip"] = "设置 Provider / API Key / 主题",
        ["region.enterHintShort"] = "点「编辑图片」开始圈画要修改的区域",
        ["region.undoTipShort"] = "撤销上一步标注编辑",
        ["region.centerTipShort"] = "把图片复位到预览框中央",
        ["param.extractTipJimengLong"] = "即梦素材提取：从当前图提取商品（衣服/鞋/包/沙发/日用品/饰品）或元素（图案/包装/logo/纹理）",
        ["param.promptGuideTipLong"] = "提示词工程指南：当前端点偏好怎么写提示词（标签页切换 总览 / OpenAI / 千问）",
        ["settings.endpointExample"] = "端点 base_url，如 https://api.openai.com/v1",
        ["settings.modelExample"] = "模型名，如 gpt-4o-mini",
        ["settings.polishKeyHint"] = "润色 API key（留空不改）",
        ["settings.uiOptions"] = "界面选项",
        ["settings.hoverAnimTip"] = "鼠标移到按钮上时的背景过渡动效；关闭则瞬时切换",
        ["settings.tooltipsTip"] = "鼠标悬停时弹出按钮功能说明；关闭则不弹",
        ["settings.languageTip"] = "切换界面语言 / Switch UI language / UI 言語を切り替え",
        ["settings.offline"] = "离线模式（调试）",
        ["settings.offlineTip"] = "不联网、用确定性占位图跑通流程（仅调试用）",
        ["settings.diagLog"] = "诊断日志",
        ["settings.diagLogTip"] = "info / warn / error 分级写入 log/，含错误原因与位置",
        ["settings.openLogTip"] = "打开 log 文件夹查看分级日志",
        ["settings.openLog"] = "打开日志目录",
        ["settings.saveAndClose"] = "保存并关闭浮层",
        ["settings.closeDialog"] = "关闭浮层",
        ["polish.title"] = "润色候选",
        ["polish.style"] = "提示词风格",
        ["polish.styleTip"] = "决定用哪套专用提示词生成候选：GPT Image 与千问的写法要求不同",
        ["polish.guideTip"] = "打开提示词工程指南（标签页切换两个端点）",
        ["polish.viewGuide"] = "查看指南",
        ["common.prev"] = "上一条",
        ["common.next"] = "下一条",
        ["common.regenerate"] = "重新生成",
        ["common.useThis"] = "采用这条",
        ["guide.title"] = "提示词工程指南",
        ["guide.subtitle"] = "按端点分别优化：同一句要求，两个端点偏好的写法不同",
        ["extract.title"] = "素材提取（即梦）",
        ["extract.product"] = "商品提取（6 种）",
        ["extract.element"] = "元素提取（4 种）",
        ["extract.objectName"] = "物件名",
        ["extract.objectNameTip"] = "留空 = 用文档原文；可填「耳坠」「项链」等具体物品",
        ["extract.inputTip"] = "输入图 = 当前预览中的图（或第一张参考图）；提取按次计费",
        ["extract.start"] = "开始提取",
        ["window.minimize"] = "最小化",
        ["window.maximize"] = "最大化 / 还原",
        ["adv.tip"] = "按官方文档提供的进阶参数（不同 provider 支持的项不同）",
        ["adv.title"] = "高级参数（按官方文档）",
        ["adv.background"] = "背景",
        ["adv.backgroundTip"] = "transparent 仅支持 png / webp（JPEG 无 Alpha 通道）；GPT Image 2/2.5 不支持 transparent",
        ["adv.compression"] = "压缩",
        ["adv.compressionTip"] = "0 = 不传；仅对 jpeg / webp 生效（png 会被忽略）",
        ["adv.moderation"] = "审核",
        ["adv.moderationTip"] = "APIMart 未传时用服务端默认 low",
        ["adv.seed"] = "种子",
        ["adv.seedTip"] = "留空 = 不传（部分模型不支持）",
        ["adv.streamTip"] = "仅支持原生流式的模型会推部分图预览；不产生额外计费",
        ["adv.streamTipOpenAI"] = "GPT Image 系支持 stream=true；dall-e-3 不支持（会自动按非流式请求）",
        ["adv.partialImages"] = "部分图数",
        ["adv.partialImagesTip"] = "partial_images：0~3。0 = 只收最终图；越大预览越连贯",
        ["adv.inputFidelity"] = "输入保真",
        ["adv.inputFidelityTip"] = "input_fidelity：high 更贴近输入图细节（尤其人脸），但更慢更贵",
        ["adv.style"] = "风格",
        ["adv.styleTip"] = "style：vivid = 更戏剧化；natural = 更自然（仅 dall-e-3）",
        ["adv.negativePrompt"] = "反向提示",
        ["adv.negativePromptTip"] = "negative_prompt：不想出现的内容",
        ["adv.promptExtend"] = "提示词智能改写（prompt_extend）",
        ["adv.promptExtendTip"] = "文档默认开启，建议保留：模型会先优化提示词再生成",
        ["adv.extendMode"] = "改写方式",
        ["adv.extendModeTip"] = "direct = 通用；agent = 更精细但仅文生图支持（图生图会自动降级为 direct）",
        ["adv.watermark"] = "添加水印（watermark）",
        ["adv.watermarkTip"] = "文档默认不加；勾选后生成图右下角带「千问」水印",
        ["adv.jimeng"] = "即梦（火山引擎）",
        ["adv.textWeight"] = "文本权重",
        ["adv.textWeightTip"] = "scale：文本描述影响程度（0~1，默认 0.5）。越大 = 文本影响越强、参考图影响越弱",
        ["adv.forceSingle"] = "强制只出 1 张（force_single）",
        ["adv.forceSingleTip"] = "模型默认按提示词意图决定出图数量（最多 15 张，按张计费）。对延迟/价格敏感时勾选",
        ["adv.loraWeight"] = "LoRA 权重",
        ["adv.loraWeightTip"] = "lora_weight：仅「元素提取」链路支持（默认 1.000）",
        ["adv.returnUrl"] = "查询结果同时返回图片链接（return_url）",
        ["adv.returnUrlTip"] = "文档：链接有效期 24 小时。结果以 base64 + 链接同时返回（base64 更稳，链接便于排查）",
        ["adv.logoInfo"] = "添加明水印（logo_info）",
        ["adv.logoInfoTip"] = "req_json.logo_info：在生成图上加文字水印",
        ["adv.logoText"] = "水印文字",
        ["adv.logoTextHint"] = "如：这里是明水印内容",
        ["hist.title"] = "历史 / 累计",
        ["hist.deleteSelectedTip"] = "完全删除选中的图片（含文件，需确认）",
        ["hist.removeSelectedTip"] = "仅从列表移除选中的项（保留文件）",
        ["hist.removeSelected"] = "移除选中",
        ["hist.multiTip"] = "开启后可在列表里多选，批量移除 / 删除",
        ["hist.importTip"] = "导入外部图片作为当前图（可继续标注编辑）",
        ["hist.import"] = "导入",
        ["hist.removeOneTip"] = "仅从列表移除（保留文件）",
        ["hist.deleteOneTip"] = "删除（含文件，需确认）",
        ["hist.totalTip"] = "全部 provider 的历史累计",
        ["hist.unknownTip"] = "早期版本生成的图片未记录 provider，金额计入「未归类」",
        ["region.toolRect"] = "方框",
        ["region.toolEllipse"] = "圆圈",
        ["region.toolMarker"] = "马克笔",
        ["region.toolEraser"] = "橡皮",
        ["region.none"] = "尚未圈画",
        ["region.count"] = "已标注 {0} 处",
        ["action.generateTipNoRef"] = "纯文生图（未附参考图）\n模型：{0} · 质量：{1}",
        ["action.generateTipWithRef"] = "文生图 + {0} 张参考图（参考图会一并发送）\n模型：{1} · 质量：{2}",
        ["action.editTipNoItem"] = "还没有可编辑的图 —— 先「生成」或「导入」一张",
        ["action.editTipWithItem"] = "以「{0}」为参考出图（第 1 位=主体）\n参考图：{1} 张自定义 + 1 张目标图\n模型：{2}",
        ["common.multi"] = "多选",
        ["common.multiDone"] = "完成多选",
        ["setup.hint"] = "尚未配置 API key —— 点右上角「⚙ 设置」填写后即可开始生成",
        ["polish.styleAuto"] = "自动（跟随生图端点）",
        ["polish.styleOpenAi"] = "OpenAI（GPT Image）",
        ["polish.styleQwen"] = "千问（Qwen-Image）",
        ["extract.hintProduct"] = "商品提取（jimeng_i2i_extract_tiled_images）：提取衣服 / 鞋 / 包 / 沙发 / 日用品 / 饰品，生成纯白背景的平视或平铺图。需 1 张输入图。",
        ["extract.hintElement"] = "元素提取（i2i_material_extraction）：从产品上提取图案 / 包装 / logo / 纹理，生成平面图并去除产品本身。需 1 张输入图。",
        ["batch.limited"] = "该模型单次仅支持 {0} 张（服务端限制）",
        ["batch.max"] = "上限 {0} 张",
        ["guide.active"] = "当前生效：{0}（润色风格 = {1}）",
        ["hist.colPosition"] = "位置",
        ["settings.languageLabel"] = "语言",
        ["region.layerAlpha"] = "不透明度",
        ["adv.providerListHint"] = "逗号分隔，如 google-ai-studio",
        ["adv.onlyProvidersTip"] = "只允许这些 provider slug 服务本次请求",
        ["adv.orderProvidersTip"] = "按此顺序优先尝试（逗号分隔）",
        ["adv.ignoreProvidersTip"] = "排除这些 slug（逗号分隔）",
        ["region.editTipHead"] = "圈画处 = 要修改的区域（当前 {0} 处）\n",
        ["region.editTipMaskUrl"] = "将发送真正的 Alpha 蒙版（mask_url）：严格限定改动区域\n目标图：{0}",
        ["region.editTipMaskField"] = "将发送真正的 Alpha 蒙版（edits 的 mask 字段）：严格限定改动区域\n目标图：{0}",
        ["region.editTipMaskGeneric"] = "将发送真正的 Alpha 蒙版：严格限定改动区域\n目标图：{0}",
        ["region.editTipNoMask"] = "{0} 文档无 mask 字段 → 将发送「原图 + 标注合成图」，模型尽力遵守\n目标图：{1}",
    };

    // ================================================================ 英文（AI 译，待母语者校对）
    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "ImgHub Workbench",
        ["common.settings"] = "Settings",
        ["common.dark"] = "Dark",
        ["common.cancel"] = "Cancel",
        ["common.close"] = "Close",
        ["common.delete"] = "Delete",
        ["common.confirm"] = "OK",
        ["common.ok"] = "OK",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.save"] = "Save",
        ["common.copy"] = "Copy",
        ["common.copied"] = "Copied",
        ["common.retry"] = "Retry",
        ["common.none"] = "None",
        ["common.unknown"] = "Unknown",

        ["param.model"] = "Model",
        ["param.quality"] = "Quality",
        ["param.aspect"] = "Aspect",
        ["param.resolution"] = "Resolution",
        ["param.format"] = "Format",
        ["param.batch"] = "Batch",
        ["param.prompt"] = "Prompt",
        ["param.extract"] = "Extract",
        ["param.genParams"] = "Parameters",
        ["param.autoModel"] = "Auto-select default model",
        ["param.promptPlaceholder"] = "A cat on a windowsill, backlit, film grain",
        ["param.genPrompt"] = "Suggest",
        ["param.genPromptTip"] = "Generate 4 prompt candidates with an LLM, pick one in the popup",
        ["param.polish"] = "Polish",
        ["param.clear"] = "Clear",
        ["param.clearTip"] = "Clear the prompt and current annotations (history is kept)",
        ["param.extractTipJimeng"] = "Jimeng material extraction: extract products or elements from the current image",
        ["param.promptGuideTip"] = "Prompting guide: preferred prompt style for the current endpoint",

        ["action.generate"] = "Generate",
        ["action.edit"] = "Edit",
        ["action.deleteSelected"] = "Delete selected",
        ["action.preview"] = "Preview",
        ["action.editImage"] = "Edit image",

        ["ref.title"] = "Reference images (attached when editing)",
        ["ref.keep"] = "Keep",
        ["ref.keepTip"] = "Checked = keep reference images; unchecked = clear after one edit (default)",
        ["ref.add"] = "+ Add",
        ["ref.addTip"] = "Import an external image as a reference for editing",

        ["promptHist.title"] = "Prompt history (hover to see full text)",
        ["promptHist.deleteSelectedTip"] = "Delete the selected prompt records (confirmation required)",
        ["promptHist.multiTip"] = "Enable multi-select in the list for batch deletion",
        ["promptHist.deleteOneTip"] = "Delete this record (confirmation required)",

        ["region.maskHint"] = "Mark the area to change with a box / circle / marker (thin overlay, original stays visible)",
        ["region.enterHint"] = "Click “Edit image” to start marking the area to change",
        ["region.tool"] = "Tool",
        ["region.brushSize"] = "Size",
        ["region.brushTip"] = "Marker stroke width / eraser radius",
        ["region.paletteTip"] = "Pick a mask color (16 colors)",
        ["region.undo"] = "Undo",
        ["region.undoTip"] = "Undo the last annotation edit (box / circle / marker / eraser / clear)",
        ["region.redo"] = "Redo",
        ["region.redoTip"] = "Redo the undone annotation edit",
        ["region.zoom"] = "Zoom",
        ["region.zoomOutTip"] = "Zoom out the preview",
        ["region.zoomInTip"] = "Zoom in the preview",
        ["region.center"] = "Center",
        ["region.centerTip"] = "Reset the image to the center of the preview (shortcut: 0)",
        ["region.clear"] = "Clear",
        ["region.clearTip"] = "Clear all annotation strokes (undoable)",
        ["region.editWithRegions"] = "Edit with marks",
        ["region.toggleTip"] = "Enable area annotation: mark the area to change",
        ["region.toolRect"] = "Box",
        ["region.toolEllipse"] = "Circle",
        ["region.toolMarker"] = "Marker",
        ["region.toolEraser"] = "Eraser",
        ["region.none"] = "Nothing marked",
        ["region.count"] = "{0} area(s) marked",

        ["bottom.viewer"] = "Open in viewer",
        ["bottom.viewerTip"] = "Open the current image with the system default viewer",
        ["bottom.saveGallery"] = "Save to gallery",
        ["bottom.saveGalleryTip"] = "Save the current image to the system pictures folder",
        ["bottom.reveal"] = "Show in folder",
        ["bottom.revealTip"] = "Reveal this image in the file manager (Windows only)",
        ["bottom.maskHelp"] = "Mask help",
        ["bottom.maskHelpTip"] = "How the mask works, what is sent to the server, and how to prompt",
        ["bottom.shortcuts"] = "Shortcuts",
        ["bottom.shortcutsTip"] = "Show available shortcuts in the message panel",
        ["bottom.dataDir"] = "Data folder",
        ["bottom.dataDirTip"] = "Show the data folder path in the message panel",
        ["bottom.undo"] = "Revert",
        ["bottom.undoTip"] = "Remove the newest item from history (file on disk is kept)",

        ["msg.title"] = "Messages",
        ["msg.stream"] = "Streaming partial image (SSE)",
        ["msg.selfCheckTip"] = "Click to see the itemized self-check",
        ["msg.cost"] = "Total",
        ["msg.costTip"] = "Accumulated cost for the current provider",

        ["settings.title"] = "Settings",
        ["settings.api"] = "Image API",
        ["settings.provider"] = "Provider",
        ["settings.apiKey"] = "API Key",
        ["settings.testKey"] = "Test",
        ["settings.testKeyTip"] = "Call the API once with the current key to verify it works",
        ["settings.endpoint"] = "Endpoint",
        ["settings.endpointHint"] = "Empty = use the official default endpoint",
        ["settings.endpointTipQwen"] = "Qwen: you may use a workspace-specific domain: https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com",
        ["settings.endpointWarnQwen"] = "Cross-region / cross-workspace calls fail auth; the endpoint must match the API key's region",
        ["settings.polish"] = "Prompt polishing (optional; needs its own endpoint/model/key)",
        ["settings.polishHint"] = "Endpoint base_url, e.g. https://...",
        ["settings.jimengAkSk"] = "Jimeng uses Volcengine AK/SK signing: AccessKeyId + SecretAccessKey",
        ["settings.jimengWhere"] = "Both keys come from the Volcengine console → Access Keys (IAM)",
        ["settings.secretAccessKey"] = "SecretAccessKey (the private key in Volcengine “Access Keys”)",
        ["settings.theme"] = "Theme",
        ["settings.darkTheme"] = "Dark theme",
        ["settings.hoverAnim"] = "Hover animation",
        ["settings.tooltips"] = "Hover tips (ToolTip)",
        ["settings.language"] = "Language / 语言",

        ["confirm.discardTip"] = "Discard changes and close this dialog",

        // ---------- v0.5.40 补充
        ["region.palette"] = "Palette",
        ["settings.darkTip"] = "Switch between dark / light theme",
        ["top.settingsTip"] = "Configure provider / API key / theme",
        ["region.enterHintShort"] = "Click “Edit image” to start marking the area to change",
        ["region.undoTipShort"] = "Undo the last annotation edit",
        ["region.centerTipShort"] = "Reset the image to the center of the preview",
        ["param.extractTipJimengLong"] = "Jimeng material extraction: extract a product (clothing/shoes/bags/sofa/household goods/accessories) or an element (pattern/package/logo/texture) from the current image",
        ["param.promptGuideTipLong"] = "Prompting guide: preferred prompt style for the current endpoint (tabs: Overview / OpenAI / Qwen)",
        ["settings.endpointExample"] = "Endpoint base_url, e.g. https://api.openai.com/v1",
        ["settings.modelExample"] = "Model name, e.g. gpt-4o-mini",
        ["settings.polishKeyHint"] = "Polish API key (leave empty to keep unchanged)",
        ["settings.uiOptions"] = "Interface",
        ["settings.hoverAnimTip"] = "Background transition when hovering a button; off = instant",
        ["settings.tooltipsTip"] = "Show a tooltip describing the button on hover; off = never show",
        ["settings.languageTip"] = "Switch UI language / 切换界面语言 / UI 言語を切り替え",
        ["settings.offline"] = "Offline mode (debug)",
        ["settings.offlineTip"] = "No network; uses deterministic placeholder images (debug only)",
        ["settings.diagLog"] = "Diagnostic log",
        ["settings.diagLogTip"] = "Writes info / warn / error into log/, including cause and location",
        ["settings.openLogTip"] = "Open the log folder to inspect leveled logs",
        ["settings.openLog"] = "Open log folder",
        ["settings.saveAndClose"] = "Save and close",
        ["settings.closeDialog"] = "Close",
        ["polish.title"] = "Polish candidates",
        ["polish.style"] = "Prompt style",
        ["polish.styleTip"] = "Which prompt set to use for candidates: GPT Image and Qwen expect different styles",
        ["polish.guideTip"] = "Open the prompting guide (tabs for both endpoints)",
        ["polish.viewGuide"] = "View guide",
        ["common.prev"] = "Previous",
        ["common.next"] = "Next",
        ["common.regenerate"] = "Regenerate",
        ["common.useThis"] = "Use this",
        ["guide.title"] = "Prompting guide",
        ["guide.subtitle"] = "Optimized per endpoint: the same request is phrased differently for each",
        ["extract.title"] = "Material extraction (Jimeng)",
        ["extract.product"] = "Product extraction (6 kinds)",
        ["extract.element"] = "Element extraction (4 kinds)",
        ["extract.objectName"] = "Object name",
        ["extract.objectNameTip"] = "Empty = use the documented text; you may specify e.g. “earrings”, “necklace”",
        ["extract.inputTip"] = "Input = the image currently in preview (or the first reference); extraction is billed per call",
        ["extract.start"] = "Start extraction",
        ["window.minimize"] = "Minimize",
        ["window.maximize"] = "Maximize / Restore",
        ["adv.tip"] = "Advanced parameters per official docs (availability differs by provider)",
        ["adv.title"] = "Advanced parameters (per official docs)",
        ["adv.background"] = "Background",
        ["adv.backgroundTip"] = "transparent supports only png / webp (JPEG has no alpha); GPT Image 2/2.5 does not support transparent",
        ["adv.compression"] = "Compression",
        ["adv.compressionTip"] = "0 = omit; applies to jpeg / webp only (png is ignored)",
        ["adv.moderation"] = "Moderation",
        ["adv.moderationTip"] = "If omitted for APIMart, the server default low is used",
        ["adv.seed"] = "Seed",
        ["adv.seedTip"] = "Empty = omit (unsupported by some models)",
        ["adv.streamTip"] = "Only models with native streaming push partial previews; no extra charge",
        ["adv.streamTipOpenAI"] = "GPT Image family supports stream=true; dall-e-3 does not (auto-falls back to non-streaming)",
        ["adv.partialImages"] = "Partial images",
        ["adv.partialImagesTip"] = "partial_images: 0–3. 0 = final image only; higher = smoother preview",
        ["adv.inputFidelity"] = "Input fidelity",
        ["adv.inputFidelityTip"] = "input_fidelity: high stays closer to input details (especially faces) but is slower and pricier",
        ["adv.style"] = "Style",
        ["adv.styleTip"] = "style: vivid = more dramatic; natural = more natural (dall-e-3 only)",
        ["adv.negativePrompt"] = "Negative prompt",
        ["adv.negativePromptTip"] = "negative_prompt: what you do not want to appear",
        ["adv.promptExtend"] = "Smart prompt rewrite (prompt_extend)",
        ["adv.promptExtendTip"] = "On by default per docs; recommended: the model optimizes the prompt before generating",
        ["adv.extendMode"] = "Rewrite mode",
        ["adv.extendModeTip"] = "direct = general; agent = finer but text-to-image only (image-to-image auto-downgrades to direct)",
        ["adv.watermark"] = "Add watermark",
        ["adv.watermarkTip"] = "Off by default per docs; when checked, a “Qwen” watermark appears at the bottom-right",
        ["adv.jimeng"] = "Jimeng (Volcengine)",
        ["adv.textWeight"] = "Text weight",
        ["adv.textWeightTip"] = "scale: how strongly the text description applies (0–1, default 0.5). Higher = stronger text, weaker reference",
        ["adv.forceSingle"] = "Force exactly one image (force_single)",
        ["adv.forceSingleTip"] = "By default the model decides the count from the prompt (up to 15, billed per image). Check when latency/cost matters",
        ["adv.loraWeight"] = "LoRA weight",
        ["adv.loraWeightTip"] = "lora_weight: supported only by the element-extraction flow (default 1.000)",
        ["adv.returnUrl"] = "Also return image links (return_url)",
        ["adv.returnUrlTip"] = "Docs: links are valid for 24 hours. Results come back as base64 + link (base64 is more reliable, links help debugging)",
        ["adv.logoInfo"] = "Add visible watermark (logo_info)",
        ["adv.logoInfoTip"] = "req_json.logo_info: adds a text watermark to the generated image",
        ["adv.logoText"] = "Watermark text",
        ["adv.logoTextHint"] = "e.g. your watermark text",
        ["hist.title"] = "History / Total",
        ["hist.deleteSelectedTip"] = "Permanently delete the selected images, files included (confirmation required)",
        ["hist.removeSelectedTip"] = "Remove the selected items from the list only (files are kept)",
        ["hist.removeSelected"] = "Remove selected",
        ["hist.multiTip"] = "Enable multi-select for batch remove / delete",
        ["hist.importTip"] = "Import an external image as the current image (annotation still available)",
        ["hist.import"] = "Import",
        ["hist.removeOneTip"] = "Remove from the list only (file is kept)",
        ["hist.deleteOneTip"] = "Delete including the file (confirmation required)",
        ["hist.totalTip"] = "Accumulated total across all providers",
        ["hist.unknownTip"] = "Images from older versions have no recorded provider; their cost counts as “Uncategorized”",
        ["region.toolRect"] = "Box",
        ["region.toolEllipse"] = "Circle",
        ["region.toolMarker"] = "Marker",
        ["region.toolEraser"] = "Eraser",
        ["region.none"] = "Nothing marked",
        ["region.count"] = "{0} area(s) marked",
        ["action.generateTipNoRef"] = "Text-to-image only (no reference)\nModel: {0} · Quality: {1}",
        ["action.generateTipWithRef"] = "Text-to-image + {0} reference image(s) (sent along)\nModel: {1} · Quality: {2}",
        ["action.editTipNoItem"] = "No image to edit yet — generate or import one first",
        ["action.editTipWithItem"] = "Use “{0}” as reference (position 1 = subject)\nReferences: {1} custom + 1 target\nModel: {2}",
        ["common.multi"] = "Multi-select",
        ["common.multiDone"] = "Done",
        ["setup.hint"] = "No API key configured — click “⚙ Settings” at the top right to start",
        ["polish.styleAuto"] = "Auto (follow image endpoint)",
        ["polish.styleOpenAi"] = "OpenAI (GPT Image)",
        ["polish.styleQwen"] = "Qwen (Qwen-Image)",
        ["extract.hintProduct"] = "Product extraction (jimeng_i2i_extract_tiled_images): extract clothing / shoes / bags / sofa / household goods / accessories; generates a flat, plain-white-background top-down or tiled image. 1 input image required.",
        ["extract.hintElement"] = "Element extraction (i2i_material_extraction): extract pattern / packaging / logo / texture from a product, generate a flat image. 1 input image required.",
        ["batch.limited"] = "This model supports only {0} image(s) per request (server limit)",
        ["batch.max"] = "Max {0}",
        ["guide.active"] = "Active: {0} (polish style = {1})",
        ["hist.colPosition"] = "Position",
        ["settings.languageLabel"] = "Language",
        ["region.layerAlpha"] = "Opacity",
        ["adv.providerListHint"] = "Comma-separated, e.g. google-ai-studio",
        ["adv.onlyProvidersTip"] = "Only these provider slugs may serve this request",
        ["adv.orderProvidersTip"] = "Try in this order first (comma-separated)",
        ["adv.ignoreProvidersTip"] = "Exclude these slugs (comma-separated)",
        ["region.editTipHead"] = "Marked areas = regions to change ({0} currently)\n",
        ["region.editTipMaskUrl"] = "A real alpha mask (mask_url) will be sent: changes strictly limited to the region\nTarget: {0}",
        ["region.editTipMaskField"] = "A real alpha mask (edits mask field) will be sent: changes strictly limited to the region\nTarget: {0}",
        ["region.editTipMaskGeneric"] = "A real alpha mask will be sent: changes strictly limited to the region\nTarget: {0}",
        ["region.editTipNoMask"] = "{0} has no mask field in its docs → sending “original + annotated composite”; the model complies best-effort\nTarget: {1}",
    };

    // ================================================================ 日文（AI 译，待母语者校对）
    private static readonly Dictionary<string, string> Ja = new()
    {
        ["app.title"] = "ImgHub ワークベンチ",
        ["common.settings"] = "設定",
        ["common.dark"] = "ダーク",
        ["common.cancel"] = "キャンセル",
        ["common.close"] = "閉じる",
        ["common.delete"] = "削除",
        ["common.confirm"] = "OK",
        ["common.ok"] = "OK",
        ["common.yes"] = "はい",
        ["common.no"] = "いいえ",
        ["common.save"] = "保存",
        ["common.copy"] = "コピー",
        ["common.copied"] = "コピーしました",
        ["common.retry"] = "再試行",
        ["common.none"] = "なし",
        ["common.unknown"] = "不明",

        ["param.model"] = "モデル",
        ["param.quality"] = "品質",
        ["param.aspect"] = "アスペクト",
        ["param.resolution"] = "解像度",
        ["param.format"] = "形式",
        ["param.batch"] = "バッチ",
        ["param.prompt"] = "プロンプト",
        ["param.extract"] = "抽出",
        ["param.genParams"] = "生成パラメータ",
        ["param.autoModel"] = "既定のモデルを自動選択",
        ["param.promptPlaceholder"] = "窓辺に座る猫、逆光、フィルム粒子",
        ["param.genPrompt"] = "候補生成",
        ["param.genPromptTip"] = "LLM でプロンプト候補を 4 つ生成し、ポップアップで 1 つ選ぶ",
        ["param.polish"] = "推敲",
        ["param.clear"] = "クリア",
        ["param.clearTip"] = "プロンプトと現在の注釈をクリア（履歴は残す）",
        ["param.extractTipJimeng"] = "Jimeng 素材抽出：現在の画像から商品や要素を抽出して平面図を生成",
        ["param.promptGuideTip"] = "プロンプトガイド：現在のエンドポイントでの推奨の書き方",

        ["action.generate"] = "生成",
        ["action.edit"] = "編集",
        ["action.deleteSelected"] = "選択を削除",
        ["action.preview"] = "プレビュー",
        ["action.editImage"] = "画像を編集",

        ["ref.title"] = "参照画像（編集時に添付）",
        ["ref.keep"] = "保持",
        ["ref.keepTip"] = "チェック = 参照画像を保持；未チェック = 1 回の編集後に自動クリア（既定）",
        ["ref.add"] = "＋ 追加",
        ["ref.addTip"] = "外部画像を参照画像として取り込む（編集時にモデルへ渡す）",

        ["promptHist.title"] = "プロンプト履歴（ホバーで全文表示）",
        ["promptHist.deleteSelectedTip"] = "選択したプロンプト記録を削除（確認あり）",
        ["promptHist.multiTip"] = "有効にするとリストで複数選択して一括削除できます",
        ["promptHist.deleteOneTip"] = "この記録を削除（確認あり）",

        ["region.maskHint"] = "変更したい領域を四角/円/マーカーで囲む（薄い重ね塗りで元画像は隠れません）",
        ["region.enterHint"] = "「画像を編集」をクリックして変更したい領域を囲んでください",
        ["region.tool"] = "ツール",
        ["region.brushSize"] = "太さ",
        ["region.brushTip"] = "マーカーの線幅 / 消しゴムの半径",
        ["region.paletteTip"] = "マスクの色を選ぶ（16 色）",
        ["region.undo"] = "元に戻す",
        ["region.undoTip"] = "直前の注釈編集を元に戻す（四角/円/マーカー/消しゴム/クリア）",
        ["region.redo"] = "やり直す",
        ["region.redoTip"] = "元に戻した注釈編集をやり直す",
        ["region.zoom"] = "ズーム",
        ["region.zoomOutTip"] = "プレビューを縮小",
        ["region.zoomInTip"] = "プレビューを拡大",
        ["region.center"] = "中央に戻す",
        ["region.centerTip"] = "画像をプレビュー中央に戻す（ショートカット: 0）",
        ["region.clear"] = "クリア",
        ["region.clearTip"] = "注釈の線をすべてクリア（元に戻せます）",
        ["region.editWithRegions"] = "注釈付きで編集",
        ["region.toggleTip"] = "領域注釈を有効化：変更したい場所を囲む",
        ["region.toolRect"] = "四角",
        ["region.toolEllipse"] = "円",
        ["region.toolMarker"] = "マーカー",
        ["region.toolEraser"] = "消しゴム",
        ["region.none"] = "未注釈",
        ["region.count"] = "{0} 箇所を注釈済み",

        ["bottom.viewer"] = "ビューアで開く",
        ["bottom.viewerTip"] = "現在の画像をシステム既定のビューアで開く",
        ["bottom.saveGallery"] = "ギャラリーに保存",
        ["bottom.saveGalleryTip"] = "現在の画像をシステムの画像フォルダに保存",
        ["bottom.reveal"] = "フォルダで表示",
        ["bottom.revealTip"] = "この画像をファイルマネージャで表示（Windows のみ）",
        ["bottom.maskHelp"] = "マスクの説明",
        ["bottom.maskHelpTip"] = "マスクの仕組み、サーバーへ送る内容、プロンプトの書き方",
        ["bottom.shortcuts"] = "ショートカット",
        ["bottom.shortcutsTip"] = "利用可能なショートカットをメッセージ欄に表示",
        ["bottom.dataDir"] = "データフォルダ",
        ["bottom.dataDirTip"] = "データフォルダのパスをメッセージ欄に表示",
        ["bottom.undo"] = "取り消し",
        ["bottom.undoTip"] = "履歴から最新の 1 件を削除（ディスク上のファイルは残ります）",

        ["msg.title"] = "メッセージ",
        ["msg.stream"] = "ストリーミング部分画像（SSE）",
        ["msg.selfCheckTip"] = "クリックで項目別のセルフチェックを表示",
        ["msg.cost"] = "累計",
        ["msg.costTip"] = "現在のプロバイダーの累計コスト",

        ["settings.title"] = "設定",
        ["settings.api"] = "画像 API",
        ["settings.provider"] = "プロバイダー",
        ["settings.apiKey"] = "API キー",
        ["settings.testKey"] = "検証",
        ["settings.testKeyTip"] = "現在のキーで API を 1 回呼び出して確認",
        ["settings.endpoint"] = "エンドポイント",
        ["settings.endpointHint"] = "空欄 = 公式の既定エンドポイントを使用",
        ["settings.endpointTipQwen"] = "Qwen はワークスペース固有ドメインを指定可：https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com",
        ["settings.endpointWarnQwen"] = "リージョン/ワークスペースを跨ぐと呼び出しが認証失敗します。エンドポイントは API キーと同じリージョンに",
        ["settings.polish"] = "プロンプト推敲（任意。専用のエンドポイント/モデル/キーが必要）",
        ["settings.polishHint"] = "エンドポイントの base_url（例: https://...）",
        ["settings.jimengAkSk"] = "Jimeng は Volcengine の AK/SK 署名認証を使用：AccessKeyId + SecretAccessKey",
        ["settings.jimengWhere"] = "両方のキーは Volcengine コンソール → アクセスキー（IAM）から取得",
        ["settings.secretAccessKey"] = "SecretAccessKey（Volcengine「アクセスキー」の秘密鍵）",
        ["settings.theme"] = "テーマ",
        ["settings.darkTheme"] = "ダークテーマ",
        ["settings.hoverAnim"] = "ホバーアニメーション",
        ["settings.tooltips"] = "ホバー説明（ToolTip）",
        ["settings.language"] = "言語 / Language",

        ["confirm.discardTip"] = "変更を破棄してこのダイアログを閉じる",

        // ---------- v0.5.40 补充
        ["region.palette"] = "パレット",
        ["settings.darkTip"] = "ダーク / ライトテーマの切り替え",
        ["top.settingsTip"] = "プロバイダー / API キー / テーマの設定",
        ["region.enterHintShort"] = "「画像を編集」をクリックして変更したい領域を囲んでください",
        ["region.undoTipShort"] = "直前の注釈編集を元に戻す",
        ["region.centerTipShort"] = "画像をプレビューの中央に戻す",
        ["param.extractTipJimengLong"] = "Jimeng 素材抽出：現在の画像から商品（衣類/靴/バッグ/ソファ/日用品/装飾品）または要素（模様/包装/ロゴ/テクスチャ）を抽出",
        ["param.promptGuideTipLong"] = "プロンプトガイド：現在のエンドポイント推奨の書き方（タブ: 概要 / OpenAI / Qwen）",
        ["settings.endpointExample"] = "エンドポイントの base_url（例: https://api.openai.com/v1）",
        ["settings.modelExample"] = "モデル名（例: gpt-4o-mini）",
        ["settings.polishKeyHint"] = "推敲用 API キー（空欄なら変更しません）",
        ["settings.uiOptions"] = "インターフェース",
        ["settings.hoverAnimTip"] = "ボタンホバー時の背景トランジション。オフ = 即時切り替え",
        ["settings.tooltipsTip"] = "ホバー時にボタンの説明を表示。オフ = 表示しない",
        ["settings.languageTip"] = "UI 言語を切り替え / Switch UI language / 切换界面语言",
        ["settings.offline"] = "オフラインモード（デバッグ）",
        ["settings.offlineTip"] = "ネットワーク不使用。決定論的なプレースホルダー画像で動作（デバッグ専用）",
        ["settings.diagLog"] = "診断ログ",
        ["settings.diagLogTip"] = "info / warn / error を log/ にレベル別に書き込み（原因と位置を含む）",
        ["settings.openLogTip"] = "log フォルダを開いてレベル別ログを確認",
        ["settings.openLog"] = "ログフォルダを開く",
        ["settings.saveAndClose"] = "保存して閉じる",
        ["settings.closeDialog"] = "閉じる",
        ["polish.title"] = "推敲候補",
        ["polish.style"] = "プロンプトのスタイル",
        ["polish.styleTip"] = "候補生成に使うプロンプトセット。GPT Image と Qwen では推奨の書き方が異なります",
        ["polish.guideTip"] = "プロンプトガイドを開く（2 つのエンドポイントをタブで切替）",
        ["polish.viewGuide"] = "ガイドを見る",
        ["common.prev"] = "前へ",
        ["common.next"] = "次へ",
        ["common.regenerate"] = "再生成",
        ["common.useThis"] = "これを使う",
        ["guide.title"] = "プロンプトガイド",
        ["guide.subtitle"] = "エンドポイント別に最適化：同じ要求でも推奨の書き方が異なります",
        ["extract.title"] = "素材抽出（Jimeng）",
        ["extract.product"] = "商品抽出（6 種）",
        ["extract.element"] = "要素抽出（4 種）",
        ["extract.objectName"] = "オブジェクト名",
        ["extract.objectNameTip"] = "空欄 = ドキュメントの原文。例「イヤリング」「ネックレス」など具体的な物品を指定可",
        ["extract.inputTip"] = "入力 = 現在プレビュー中の画像（または最初の参照画像）。抽出は 1 回ごとの課金",
        ["extract.start"] = "抽出を開始",
        ["window.minimize"] = "最小化",
        ["window.maximize"] = "最大化 / 元に戻す",
        ["adv.tip"] = "公式ドキュメント準拠の詳細パラメータ（対応項目はプロバイダーにより異なります）",
        ["adv.title"] = "詳細パラメータ（公式ドキュメント準拠）",
        ["adv.background"] = "背景",
        ["adv.backgroundTip"] = "transparent は png / webp のみ（JPEG はアルファなし）。GPT Image 2/2.5 は未対応",
        ["adv.compression"] = "圧縮",
        ["adv.compressionTip"] = "0 = 送信しない。jpeg / webp のみ有効（png は無視）",
        ["adv.moderation"] = "モデレーション",
        ["adv.moderationTip"] = "APIMart で未指定の場合、サーバー既定の low が使われます",
        ["adv.seed"] = "シード",
        ["adv.seedTip"] = "空欄 = 送信しない（一部モデルは未対応）",
        ["adv.streamTip"] = "ネイティブストリーミング対応モデルのみ部分プレビューを配信。追加課金はありません",
        ["adv.streamTipOpenAI"] = "GPT Image 系は stream=true 対応。dall-e-3 は非対応（自動で非ストリーミングに）",
        ["adv.partialImages"] = "部分画像数",
        ["adv.partialImagesTip"] = "partial_images：0〜3。0 = 最終画像のみ。大きいほどプレビューが滑らか",
        ["adv.inputFidelity"] = "入力忠実度",
        ["adv.inputFidelityTip"] = "input_fidelity：high は入力の細部（特に顔）に忠実だが、遅く高価",
        ["adv.style"] = "スタイル",
        ["adv.styleTip"] = "style：vivid = より劇的。natural = より自然（dall-e-3 のみ）",
        ["adv.negativePrompt"] = "ネガティブプロンプト",
        ["adv.negativePromptTip"] = "negative_prompt：出したくない内容",
        ["adv.promptExtend"] = "プロンプト自動改寫（prompt_extend）",
        ["adv.promptExtendTip"] = "ドキュメント既定はオン。推奨：モデルが生成前にプロンプトを最適化",
        ["adv.extendMode"] = "改寫方式",
        ["adv.extendModeTip"] = "direct = 汎用。agent = より精細だがテキスト→画像のみ（画像→画像は direct に自動降格）",
        ["adv.watermark"] = "ウォーターマークを追加",
        ["adv.watermarkTip"] = "ドキュメント既定はオフ。チェックすると生成画像の右下に「Qwen」の透かし",
        ["adv.jimeng"] = "Jimeng（Volcengine）",
        ["adv.textWeight"] = "テキストの重み",
        ["adv.textWeightTip"] = "scale：テキスト記述の影響度（0〜1、既定 0.5）。大きいほどテキストが強く参照画像が弱くなる",
        ["adv.forceSingle"] = "必ず 1 枚のみ出力（force_single）",
        ["adv.forceSingleTip"] = "既定ではプロンプトの意図から枚数を決定（最大 15 枚、1 枚ごとに課金）。遅延や価格を重視する場合にチェック",
        ["adv.loraWeight"] = "LoRA の重み",
        ["adv.loraWeightTip"] = "lora_weight：要素抽出のフローのみ対応（既定 1.000）",
        ["adv.returnUrl"] = "画像リンクも返す（return_url）",
        ["adv.returnUrlTip"] = "ドキュメント：リンクの有効期限は 24 時間。結果は base64 とリンクの両方で返ります（base64 が確実、リンクは調査に便利）",
        ["adv.logoInfo"] = "可視ウォーターマークを追加（logo_info）",
        ["adv.logoInfoTip"] = "req_json.logo_info：生成画像にテキストの透かしを追加",
        ["adv.logoText"] = "透かしの文字",
        ["adv.logoTextHint"] = "例：透かしの内容",
        ["hist.title"] = "履歴 / 累計",
        ["hist.deleteSelectedTip"] = "選択した画像を完全に削除（ファイル含む・確認あり）",
        ["hist.removeSelectedTip"] = "選択項目をリストからのみ削除（ファイルは保持）",
        ["hist.removeSelected"] = "選択を削除",
        ["hist.multiTip"] = "有効にすると複数選択して一括削除/除去ができます",
        ["hist.importTip"] = "外部画像を現在の画像として取り込む（注釈編集も可能）",
        ["hist.import"] = "取り込み",
        ["hist.removeOneTip"] = "リストからのみ削除（ファイルは保持）",
        ["hist.deleteOneTip"] = "ファイルごと削除（確認あり）",
        ["hist.totalTip"] = "全プロバイダーの累計",
        ["hist.unknownTip"] = "旧バージョンの画像はプロバイダー未記録。金額は「未分類」に計上",
        ["region.toolRect"] = "四角",
        ["region.toolEllipse"] = "円",
        ["region.toolMarker"] = "マーカー",
        ["region.toolEraser"] = "消しゴム",
        ["region.none"] = "未注釈",
        ["region.count"] = "{0} 箇所を注釈済み",
        ["action.generateTipNoRef"] = "テキストのみ（参照画像なし）\nモデル: {0} · 品質: {1}",
        ["action.generateTipWithRef"] = "テキスト + 参照画像 {0} 枚（一緒に送信）\nモデル: {1} · 品質: {2}",
        ["action.editTipNoItem"] = "編集できる画像がありません — 先に「生成」か「取り込み」を",
        ["action.editTipWithItem"] = "「{0}」を参照に生成（1 番目 = 主体）\n参照画像: カスタム {1} 枚 + 対象 1 枚\nモデル: {2}",
        ["common.multi"] = "複数選択",
        ["common.multiDone"] = "選択完了",
        ["setup.hint"] = "API キーが未設定です — 右上の「⚙ 設定」から入力してください",
        ["polish.styleAuto"] = "自動（画像エンドポイントに追従）",
        ["polish.styleOpenAi"] = "OpenAI（GPT Image）",
        ["polish.styleQwen"] = "Qwen（Qwen-Image）",
        ["extract.hintProduct"] = "商品抽出（jimeng_i2i_extract_tiled_images）：衣類 / 靴 / バッグ / ソファ / 日用品 / 装飾品を抽出し、白背景の平面図を生成。入力画像 1 枚が必要。",
        ["extract.hintElement"] = "要素抽出（i2i_material_extraction）：製品から模様 / 包装 / ロゴ / テクスチャを抽出し平面図を生成。入力画像 1 枚が必要。",
        ["batch.limited"] = "このモデルは 1 回につき {0} 枚まで（サーバー制限）",
        ["batch.max"] = "上限 {0} 枚",
        ["guide.active"] = "現在有効：{0}（推敲スタイル = {1}）",
        ["hist.colPosition"] = "位置",
        ["settings.languageLabel"] = "言語",
        ["region.layerAlpha"] = "不透明度",
        ["adv.providerListHint"] = "カンマ区切り（例: google-ai-studio）",
        ["adv.onlyProvidersTip"] = "これらのプロバイダー slug のみが本リクエストを処理できます",
        ["adv.orderProvidersTip"] = "この順序で優先的に試行（カンマ区切り）",
        ["adv.ignoreProvidersTip"] = "これらの slug を除外（カンマ区切り）",
        ["region.editTipHead"] = "囲んだ箇所 = 変更する領域（現在 {0} 箇所）\n",
        ["region.editTipMaskUrl"] = "本物のアルファマスク（mask_url）を送信します：変更領域を厳密に限定\n対象: {0}",
        ["region.editTipMaskField"] = "本物のアルファマスク（edits の mask フィールド）を送信します：変更領域を厳密に限定\n対象: {0}",
        ["region.editTipMaskGeneric"] = "本物のアルファマスクを送信します：変更領域を厳密に限定\n対象: {0}",
        ["region.editTipNoMask"] = "{0} のドキュメントに mask フィールドなし → 「元画像 + 注釈合成画像」を送信。モデルはベストエフォートで従います\n対象: {1}",
    };
}
